name: demo_app
description: "A demo Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  equatable: ^2.0.5
  get_it: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  infinite_scroll_pagination: ^4.0.0
  meta: ^1.12.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  test: ^1.25.2

flutter:
  uses-material-design: true
